services:
  db:
    image: mysql:8.0
    container_name: mysql_mike
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'mike'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8222"
    volumes:
      - .:/app
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost
      - DATABASE_URL=mysql://root:123456@db:3306/mike
    ports:
      - "8222:8222"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork: