version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8111"
    volumes:
      - .:/app
    ports:
      - "8222:8222"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork: