# Generated by Django 4.2.14 on 2024-08-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchamodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
